language: php

php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
    - phpenv config-rm xdebug.ini
    - phpenv config-add travis.php.ini
    - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    - composer self-update --no-interaction

install:
    - composer install --prefer-dist --no-interaction

script:
    - bin/php-cs-fixer fix --diff --dry-run --config=.php_cs.php -vvv
    - bin/phpspec run --no-interaction
    - php -d error_reporting="E_ALL" bin/phpunit -c phpunit.xml.dist

notifications:
  email: false
