version: 2.1

jobs:
  build_and_test:
    docker:
      - image: akeneo/php:7.2
    steps:
      - checkout
      - run: composer install
      - run: bin/phpunit -c phpunit.xml.dist
      - run: bin/phpspec run
      - run: bin/php-cs-fixer fix --diff --dry-run --config=.php_cs.php -vvv

workflows:
  pull_request:
    jobs:
      - wait_for_user_approval:
          type: approval
          filters:
            branches:
              ignore:
                - master
      - build_and_test:
          requires:
            - wait_for_user_approval
