version: 2.1

jobs:
    build:
        docker:
            -   image: akeneo/php:7.2
        steps:
            -   checkout
            -   run: composer install
            -   persist_to_workspace:
                    root: ~/
                    paths:
                        - project

    test_php:
        docker:
            -   image: akeneo/php:7.2
        steps:
            -   attach_workspace:
                    at: ~/
            -   run: bin/phpunit -c phpunit.xml.dist
            -   run: bin/phpspec run

    test_php_code_style:
        docker:
            -   image: akeneo/php:7.2
        steps:
            -   attach_workspace:
                    at: ~/
            -   run: bin/php-cs-fixer fix --diff --dry-run --config=.php_cs.php -vvv

    workflow_success:
        docker:
            -   image: akeneo/php:7.2
        steps:
            - run:
                  name: Success
                  command: echo "The build has run with success! Let's merge :)"

workflows:
    pull_request:
        jobs:
            -   wait_for_user_approval:
                    type: approval
                    filters:
                        branches:
                            ignore:
                                - master
            -   build:
                    requires:
                        - wait_for_user_approval
            -   test_php:
                    requires:
                        - build
            -   test_php_code_style:
                    requires:
                        - build
            -   workflow_success:
                    requires:
                        - test_php
                        - test_php_code_style

    after_merge:
        jobs:
            -   build:
                    filters:
                        branches:
                            only:
                                - master
            -   test_php:
                    requires:
                        - build
            -   test_php_code_style:
                    requires:
                        - build

    nightly:
        when:
            and:
                -   equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
                -   equal: [ "nightly_master", << pipeline.schedule.name >> ]
        jobs:
            -   build
            -   test_php:
                    requires:
                        -   build
